set = "RV32F"
width = 32

[types]
names = [
    "load",
    "store",
    "madd",
    "msub",
    "nmadd",
    "nmsub",
    "arith",
    "f2i",
    "i2f",
    "if",
]
parts = [
    [
        "opcode",
        7,
        "u8",
    ],
    [
        "funct3",
        3,
        "u8",
    ],
    [
        "rm",
        3,
        "u8",
    ],
    [
        "funct5",
        5,
        "u8",
    ],
    [
        "fmt",
        2,
        "u8",
    ],
    [
        "rdi",
        5,
        "Register_int",
    ],
    [
        "rs1i",
        5,
        "Register_int",
    ],
    [
        "rdf",
        5,
        "Register_float",
    ],
    [
        "rs1f",
        5,
        "Register_float",
    ],
    [
        "rs2f",
        5,
        "Register_float",
    ],
    [
        "rs3f",
        5,
        "Register_float",
    ],
    [
        "imm",
        32,
        "VInt",
    ],
]

[type]
names = ["Rfff", "Rfif", "Rffi", "I", "S", "R4"]
Rfff = [
    { name = "funct5", top = 4, bot = 0 },
    { name = "fmt", top = 1, bot = 0 },
    { name = "rs2f", top = 4, bot = 0 },
    { name = "rs1f", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rdf", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
Rfif = [
    { name = "funct5", top = 4, bot = 0 },
    { name = "fmt", top = 1, bot = 0 },
    { name = "rs2f", top = 4, bot = 0 },
    { name = "rs1i", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rdf", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
Rffi = [
    { name = "funct5", top = 4, bot = 0 },
    { name = "fmt", top = 1, bot = 0 },
    { name = "rs2f", top = 4, bot = 0 },
    { name = "rs1f", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rdi", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
I = [
    { name = "imm", top = 11, bot = 0 },
    { name = "rs1i", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "rdf", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
S = [
    { name = "imm", top = 11, bot = 5 },
    { name = "rs2f", top = 4, bot = 0 },
    { name = "rs1i", top = 4, bot = 0 },
    { name = "funct3", top = 2, bot = 0 },
    { name = "imm", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]
R4 = [
    { name = "rs3f", top = 4, bot = 0 },
    { name = "fmt", top = 1, bot = 0 },
    { name = "rs2f", top = 4, bot = 0 },
    { name = "rs1f", top = 4, bot = 0 },
    { name = "rm", top = 2, bot = 0 },
    { name = "rdf", top = 4, bot = 0 },
    { name = "opcode", top = 6, bot = 0 },
]

[reg]
repr = "$name$ %rd%, %rs1%, %rs2%"
type = "R"
opcode = 0b0110011
substitutions = {}
[reg.instructions]
add = { funct3 = 0x0, funct7 = 0x00 }
sub = { funct3 = 0x0, funct7 = 0x20 }
xor = { funct3 = 0x4, funct7 = 0x00 }
or = { funct3 = 0x6, funct7 = 0x00 }
and = { funct3 = 0x7, funct7 = 0x00 }
sll = { funct3 = 0x1, funct7 = 0x00 }
srl = { funct3 = 0x5, funct7 = 0x00 }
sra = { funct3 = 0x5, funct7 = 0x20 }
slt = { funct3 = 0x2, funct7 = 0x00 }
sltu = { funct3 = 0x3, funct7 = 0x00 }

[load]
repr = "$name$ %rdf%, %imm%(%rs1i%)"
type = "I"
opcode = 0b0000111
substitutions = {}
[load.instructions]
flw = { rm = 0b010 }

[store]
repr = "$name$ %rdf%, %imm%(%rs1i%)"
type = "S"
opcode = 0b0100111
substitutions = {}
[store.instructions]
fsw = { rm = 0b010 }

[madd]
repr = "$name$ %rdf%, %rs1f%, %rs2f%, %rs3f%"
type = "R4"
opcode = 0b1000011
substitutions = {}
[madd.instructions]
fmadd_s = { fmt = 0b00, rm = 0b111 }

[msub]
repr = "$name$ %rdf%, %rs1f%, %rs2f%, %rs3f%"
type = "R4"
opcode = 0b1000111
substitutions = {}
[msub.instructions]
fmsub_s = { fmt = 0b00, rm = 0b111 }

[nmadd]
repr = "$name$ %rdf%, %rs1f%, %rs2f%, %rs3f%"
type = "R4"
opcode = 0b1001111
substitutions = {}
[nmadd.instructions]
fnmadd_s = { fmt = 0b00, rm = 0b111 }

[nmsub]
repr = "$name$ %rdf%, %rs1f%, %rs2f%, %rs3f%"
type = "R4"
opcode = 0b1001011
substitutions = {}
[nmsub.instructions]
fnmsub_s = { fmt = 0b00, rm = 0b111 }

[arith]
repr = "$name$ %rdf%, %rs1f%, %rs2f%"
type = "Rfff"
opcode = 0b1010011
substitutions = {}
[arith.instructions]
fadd_s = { funct5 = 0b00000, fmt = 0b00, rm = 0b111 }
fsub_s = { funct5 = 0b00001, fmt = 0b00, rm = 0b111 }
fmul_s = { funct5 = 0b00010, fmt = 0b00, rm = 0b111 }
fdiv_s = { funct5 = 0b00011, fmt = 0b00, rm = 0b111 }
fsgnj_s = { funct5 = 0b00100, fmt = 0b00, rm = 0b000 }
fsgnjn_s = { funct5 = 0b00100, fmt = 0b00, rm = 0b001 }
fsgnjx_s = { funct5 = 0b00100, fmt = 0b00, rm = 0b010 }
fmin_s = { funct5 = 0b00101, fmt = 0b00, rm = 0b000 }
fmax_s = { funct5 = 0b00101, fmt = 0b00, rm = 0b001 }
fsqrt_s = { funct5 = 0b01011, fmt = 0b00, rm = 0b111 }

[i2f]
repr = "$name$ %rdf% %rs1i%"
type = "Rfif"
opcode = 0b1010011
substitutions = {}
[i2f.instructions]
fcvt_s_w = { rs2f = 0b00000, funct5 = 0b11010, fmt = 0b00, rm = 0b111 }
fcvt_s_wu = { rs2f = 0b00001, funct5 = 0b11010, fmt = 0b00, rm = 0b111 }
fmv_w_x = { rs2f = 0b00000, funct5 = 0b11110, fmt = 0b00, rm = 0b000 }

[f2i]
repr = "$name$ %rdi% %rs1f%"
type = "Rffi"
opcode = 0b1010011
substitutions = {}
[f2i.instructions]
fcvt_w_s = { rs2f = 0b00000, funct5 = 0b11000, fmt = 0b00, rm = 0b111 }
fcvt_wu_s = { rs2f = 0b00001, funct5 = 0b11000, fmt = 0b00, rm = 0b111 }
fmv_x_w = { rs2f = 0b00000, funct5 = 0b11100, fmt = 0b00, rm = 0b000 }
fclass_s = { rs2f = 0b00000, funct5 = 0b11100, fmt = 0b00, rm = 0b001 }

[if]
repr = "$name$ %rdi%, %rs1f%, %rs2f%"
type = "Rffi"
opcode = 0b1010011
substitutions = {}
[if.instructions]
feq_s = { funct5 = 0b10100, fmt = 0b00, rm = 0b010 }
flt_s = { funct5 = 0b10100, fmt = 0b00, rm = 0b001 }
fle_s = { funct5 = 0b10100, fmt = 0b00, rm = 0b000 }

[register]
names = ["Register_int", "Register_float"]
number = 32
Register_int = [
    "zero",
    "ra",
    "sp",
    "gp",
    "tp",
    "t0",
    "t1",
    "t2",
    "s0",
    "s1",
    "a0",
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "s2",
    "s3",
    "s4",
    "s5",
    "s6",
    "s7",
    "s8",
    "s9",
    "s10",
    "s11",
    "t3",
    "t4",
    "t5",
    "t6",
]

Register_float = [
    "ft0",
    "ft1",
    "ft2",
    "ft3",
    "ft4",
    "ft5",
    "ft6",
    "ft7",
    "fs0",
    "fs1",
    "fa0",
    "fa1",
    "fa2",
    "fa3",
    "fa4",
    "fa5",
    "fa6",
    "fa7",
    "fs2",
    "fs3",
    "fs4",
    "fs5",
    "fs6",
    "fs7",
    "fs8",
    "fs9",
    "fs10",
    "fs11",
    "ft8",
    "ft9",
    "ft10",
    "ft11",
]
